import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

	return (
		<html lang="en" className="">
			<body className={`${inter.className}`}>
				{children}
				<footer className="fixed bottom-0 w-full bg-red-800">
					<p>Um projeto de estudo feito por Matheus Caldas</p>
				</footer>
			</body>
		</html>
	);
}
